<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>true</IsPackable>
		<LangVersion>11.0</LangVersion>

		<Title>$(AssemblyName)</Title>
		<Authors>2code</Authors>
		<PackageProjectUrl>https://github.com/2code-it/Code2.Web.SseTyped</PackageProjectUrl>
		<PackageTags>server sent events typed</PackageTags>
		<RepositoryUrl>https://github.com/2code-it/Code2.Web.SseTyped.git</RepositoryUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Description>AspNet server sent events tools to emit typed messages</Description>
		<PackageLicenseExpression>BSD-2-Clause</PackageLicenseExpression>
		<OutputType>Library</OutputType>
		<Deterministic>true</Deterministic>
		<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.4" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="9.0.4" />
	</ItemGroup>



	<ItemGroup Condition="'$(TargetFramework)'=='netstandard2.0'">
		<PackageReference Include="System.Text.Json" Version="9.0.4" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

</Project>